[theme]
base = "dark"
primaryColor = "#9333ea"
backgroundColor = "#0F172A"
secondaryBackgroundColor = "#1E293B"
textColor = "#F8FAFC"
font = "sans serif"

[theme.sidebar]
backgroundColor = "#0F172A"
secondaryBackgroundColor = "#1E293B"
textColor = "#E6F1FF"
